### ISSUE TITLE
Add every league

### ISSUE THREAD

**Issue by bboldizsarHU** [dimasikson/football-prediction-web-app#3]
Hi,
Very good project, congrats!

May I ask you to add every league (which is available @ football-data.co.uk, like the Greek, Turkey, Scotland 1st and 2nd league etc) if possible?

Thank you very much!

**Comment by dimasikson** [comment]
Hey, thanks for the input, I added them :) also added Belgium. Other leagues on there don't have very complete data.

https://github.com/dimasikson/football-prediction-web-app/blob/master/config.py#L28-L31
